# Generated by Django 4.1.2 on 2023-04-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_id',
            new_name='email',
        ),
    ]
